name: Cart test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          DB_READER_USER: reader_user
          DB_READER_PASSWORD: reader_password
          DB_WRITER_USER: writer_user
          DB_WRITER_PASSWORD: writer_password
          DB_NAME: local_dev
          DB_SHADOW_NAME: local_dev_shadow
          DB_HOST: 127.0.0.1
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - name: Set up MySQL
        run: |
          bash ./scripts/dbSetup.sh

      - name: Install dependencies
        working-directory: ./packages/server
        run: |
          npm install

      - name: Start MySQL
        working-directory: ./packages/server
        run: |
          npm run prisma:reset:force

      - name: Start Node.js server
        working-directory: ./packages/server
        run: |
          npm run start:ci

      - name: Run tests
        working-directory: ./packages/server
        run: |
          npm run test
